#!/usr/bin/env bash

# config file path
CONFIG_FILE="$HOME/.config/nixos/configuration.nix"
UEFI_CONFIG_FILE="$HOME/.config/nixos/nixos-uefi.nix"

# Ask user for UEFI choice
read -p "Do you want to use UEFI? (yes/no): " USE_UEFI_INPUT

# Set USE_UEFI based on user input
if [[ "$USE_UEFI_INPUT" == "yes" || "$USE_UEFI_INPUT" == "y" ]]; then
    USE_UEFI=true
else
    USE_UEFI=false
fi

# Determine the config file to use based on the UEFI setting
if [ "$USE_UEFI" = true ]; then
    CONFIG_FILE="$UEFI_CONFIG_FILE"
fi

# Check if the configuration file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Configuration file not found: $CONFIG_FILE"
    exit 1
fi

# Create a symlink to the nixos hardware config file
if [ ! -L ~/.config/nixos/hardware-configuration.nix ]; then
    ln -s /etc/nixos/hardware-configuration.nix ~/.config/nixos/hardware-configuration.nix
fi

# Run the nixos-rebuild command
sudo nixos-rebuild switch -I nixos-config="$CONFIG_FILE"

# To run this file use the command: os-rebuild
